import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { employeeAPI } from '../../apis';

/**
 * Create Employee Component
 * Allows HR/Admin to create new employees
 * 
 * Features:
 * - Form validation
 * - Direct API calls (no Redux)
 * - Loading and error states
 * - Success message
 */
const CreateEmployee = () => {
  const navigate = useNavigate();
  
  // Local state for loading, error, and success
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);
  
  // Form state
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    email: '',
    yearOfJoining: '',
    mobileNumber: '',
    department: '',
    manager: '',
    location: '',
    jobPosition: '',
  });
  
  const [formErrors, setFormErrors] = useState({});

  /**
   * Handle input change
   */
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    // Clear field error when user starts typing
    if (formErrors[name]) {
      setFormErrors((prev) => ({
        ...prev,
        [name]: '',
      }));
    }
    // Clear error when user starts typing
    if (error) {
      setError(null);
    }
  };

  /**
   * Validate form fields
   */
  const validateForm = () => {
    const errors = {};
    
    if (!formData.firstName.trim()) {
      errors.firstName = 'First name is required';
    }
    
    if (!formData.lastName.trim()) {
      errors.lastName = 'Last name is required';
    }
    
    if (!formData.email.trim()) {
      errors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      errors.email = 'Email is invalid';
    }
    
    if (!formData.yearOfJoining) {
      errors.yearOfJoining = 'Year of joining is required';
    } else {
      const currentYear = new Date().getFullYear();
      const year = parseInt(formData.yearOfJoining);
      if (year < 1900 || year > currentYear) {
        errors.yearOfJoining = `Year must be between 1900 and ${currentYear}`;
      }
    }
    
    if (!formData.mobileNumber.trim()) {
      errors.mobileNumber = 'Mobile number is required';
    } else if (!/^\d{10}$/.test(formData.mobileNumber.replace(/\D/g, ''))) {
      errors.mobileNumber = 'Mobile number must be 10 digits';
    }
    
    if (!formData.department) {
      errors.department = 'Department is required';
    }
    
    if (!formData.manager.trim()) {
      errors.manager = 'Manager is required';
    }
    
    if (!formData.location.trim()) {
      errors.location = 'Location is required';
    }
    
    if (!formData.jobPosition.trim()) {
      errors.jobPosition = 'Job position is required';
    }
    
    setFormErrors(errors);
    return Object.keys(errors).length === 0;
  };

  /**
   * Handle form submission
   */
  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Clear previous errors
    setFormErrors({});
    setError(null);
    setSuccess(false);
    
    // Validate form
    if (!validateForm()) {
      return;
    }
    
    // Set loading state
    setLoading(true);
    
    try {
      // Call API directly
      await employeeAPI.create(formData);
      
      // Success
      setSuccess(true);
      setLoading(false);
      
      // Clear form after 3 seconds
      setTimeout(() => {
        setFormData({
          firstName: '',
          lastName: '',
          email: '',
          yearOfJoining: '',
          mobileNumber: '',
          department: '',
          manager: '',
          location: '',
          jobPosition: '',
        });
        setFormErrors({});
        setSuccess(false);
      }, 3000);
    } catch (err) {
      // Error handling
      setLoading(false);
      setError(
        err.response?.data?.message || 'Failed to create employee. Please try again.'
      );
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 px-4 py-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">Create New Employee</h1>
          <p className="text-gray-400">Fill in the employee details below</p>
        </div>

        {/* Success Message */}
        {success && (
          <div className="mb-6 p-4 bg-green-500/10 border border-green-500/30 rounded-xl text-green-400">
            <p className="font-semibold">Employee created successfully!</p>
            <p className="text-sm mt-1">Credentials will be generated by the system.</p>
          </div>
        )}

        {/* Error Message */}
        {error && (
          <div className="mb-6 p-4 bg-red-500/10 border border-red-500/30 rounded-xl text-red-400">
            {error}
          </div>
        )}

        {/* Form Card */}
        <div className="bg-slate-800/90 backdrop-blur-sm rounded-2xl shadow-2xl border border-purple-500/20 p-8">
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* First Name and Last Name */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="firstName" className="block text-sm font-medium text-gray-300 mb-2">
                  First Name <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  id="firstName"
                  name="firstName"
                  className="w-full px-4 py-3 bg-slate-700/50 border border-purple-500/30 rounded-xl text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                  placeholder="Enter first name"
                  value={formData.firstName}
                  onChange={handleChange}
                />
                {formErrors.firstName && (
                  <p className="mt-2 text-sm text-red-400">{formErrors.firstName}</p>
                )}
              </div>

              <div>
                <label htmlFor="lastName" className="block text-sm font-medium text-gray-300 mb-2">
                  Last Name <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  id="lastName"
                  name="lastName"
                  className="w-full px-4 py-3 bg-slate-700/50 border border-purple-500/30 rounded-xl text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                  placeholder="Enter last name"
                  value={formData.lastName}
                  onChange={handleChange}
                />
                {formErrors.lastName && (
                  <p className="mt-2 text-sm text-red-400">{formErrors.lastName}</p>
                )}
              </div>
            </div>

            {/* Email */}
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-300 mb-2">
                Email ID <span className="text-red-400">*</span>
              </label>
              <input
                type="email"
                id="email"
                name="email"
                className="w-full px-4 py-3 bg-slate-700/50 border border-purple-500/30 rounded-xl text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                placeholder="Enter email address"
                value={formData.email}
                onChange={handleChange}
              />
              {formErrors.email && (
                <p className="mt-2 text-sm text-red-400">{formErrors.email}</p>
              )}
            </div>

            {/* Year of Joining and Mobile Number */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="yearOfJoining" className="block text-sm font-medium text-gray-300 mb-2">
                  Year of Joining <span className="text-red-400">*</span>
                </label>
                <input
                  type="number"
                  id="yearOfJoining"
                  name="yearOfJoining"
                  className="w-full px-4 py-3 bg-slate-700/50 border border-purple-500/30 rounded-xl text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                  placeholder="e.g., 2024"
                  min="1900"
                  max={new Date().getFullYear()}
                  value={formData.yearOfJoining}
                  onChange={handleChange}
                />
                {formErrors.yearOfJoining && (
                  <p className="mt-2 text-sm text-red-400">{formErrors.yearOfJoining}</p>
                )}
              </div>

              <div>
                <label htmlFor="mobileNumber" className="block text-sm font-medium text-gray-300 mb-2">
                  Mobile Number <span className="text-red-400">*</span>
                </label>
                <input
                  type="tel"
                  id="mobileNumber"
                  name="mobileNumber"
                  className="w-full px-4 py-3 bg-slate-700/50 border border-purple-500/30 rounded-xl text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                  placeholder="Enter mobile number"
                  value={formData.mobileNumber}
                  onChange={handleChange}
                />
                {formErrors.mobileNumber && (
                  <p className="mt-2 text-sm text-red-400">{formErrors.mobileNumber}</p>
                )}
              </div>
            </div>

            {/* Department and Manager */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="department" className="block text-sm font-medium text-gray-300 mb-2">
                  Department <span className="text-red-400">*</span>
                </label>
                <select
                  id="department"
                  name="department"
                  className="w-full px-4 py-3 bg-slate-700/50 border border-purple-500/30 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                  value={formData.department}
                  onChange={handleChange}
                >
                  <option value="">Select department</option>
                  <option value="HR">HR</option>
                  <option value="IT">IT</option>
                  <option value="Finance">Finance</option>
                  <option value="Marketing">Marketing</option>
                  <option value="Sales">Sales</option>
                  <option value="Operations">Operations</option>
                  <option value="Engineering">Engineering</option>
                  <option value="Design">Design</option>
                </select>
                {formErrors.department && (
                  <p className="mt-2 text-sm text-red-400">{formErrors.department}</p>
                )}
              </div>

              <div>
                <label htmlFor="manager" className="block text-sm font-medium text-gray-300 mb-2">
                  Manager <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  id="manager"
                  name="manager"
                  className="w-full px-4 py-3 bg-slate-700/50 border border-purple-500/30 rounded-xl text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                  placeholder="Enter manager name"
                  value={formData.manager}
                  onChange={handleChange}
                />
                {formErrors.manager && (
                  <p className="mt-2 text-sm text-red-400">{formErrors.manager}</p>
                )}
              </div>
            </div>

            {/* Location and Job Position */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="location" className="block text-sm font-medium text-gray-300 mb-2">
                  Location <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  id="location"
                  name="location"
                  className="w-full px-4 py-3 bg-slate-700/50 border border-purple-500/30 rounded-xl text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                  placeholder="Enter location"
                  value={formData.location}
                  onChange={handleChange}
                />
                {formErrors.location && (
                  <p className="mt-2 text-sm text-red-400">{formErrors.location}</p>
                )}
              </div>

              <div>
                <label htmlFor="jobPosition" className="block text-sm font-medium text-gray-300 mb-2">
                  Job Position <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  id="jobPosition"
                  name="jobPosition"
                  className="w-full px-4 py-3 bg-slate-700/50 border border-purple-500/30 rounded-xl text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                  placeholder="Enter job position"
                  value={formData.jobPosition}
                  onChange={handleChange}
                />
                {formErrors.jobPosition && (
                  <p className="mt-2 text-sm text-red-400">{formErrors.jobPosition}</p>
                )}
              </div>
            </div>

            {/* Submit Button */}
            <div className="flex gap-4 pt-4">
              <button
                type="submit"
                className="flex-1 py-3 bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800 text-white font-semibold rounded-xl shadow-lg hover:shadow-purple-500/50 transition-all duration-300 disabled:opacity-60 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                disabled={loading}
              >
                {loading && (
                  <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                )}
                {loading ? 'Creating Employee...' : 'Create Employee'}
              </button>
              
              <button
                type="button"
                onClick={() => navigate('/dashboard')}
                className="px-6 py-3 bg-slate-700 hover:bg-slate-600 text-white font-semibold rounded-xl transition-all duration-300"
              >
                Cancel
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default CreateEmployee;
